table transactions
	lineageTag: 8382a8fb-04e8-43b3-8303-353b24110612

	column transaction_id
		dataType: string
		lineageTag: 114dafbb-b4cd-405b-8d59-a70f59116bc1
		summarizeBy: none
		sourceColumn: transaction_id

		annotation SummarizationSetBy = Automatic

	column session_id
		dataType: int64
		formatString: 0
		lineageTag: abb434d5-02ae-4510-a4c9-2c04869a9aa9
		summarizeBy: none
		sourceColumn: session_id

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 39095c2d-fa05-41cf-8753-8b395d94604d
		summarizeBy: none
		sourceColumn: order_date

		variation Variation
			isDefault
			relationship: b9a569a9-449a-4a17-b327-8db594d8bd8b
			defaultHierarchy: LocalDateTable_895f5800-2ffe-493f-b863-0f169cfd9de3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column gross_revenue
		dataType: decimal
		lineageTag: cad49e69-e69c-4e41-ac0b-d1f275ccbc6f
		summarizeBy: sum
		sourceColumn: gross_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column discount_amount
		dataType: decimal
		lineageTag: cf62c5bf-fce7-49f9-a93e-38cc7b0f317e
		summarizeBy: sum
		sourceColumn: discount_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column net_revenue
		dataType: decimal
		lineageTag: ba2ba6ac-767d-424c-a6bb-c886af8a6945
		summarizeBy: sum
		sourceColumn: net_revenue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column items_count
		dataType: int64
		formatString: 0
		lineageTag: 99dccfb5-2124-4f31-b031-72c32df8bc88
		summarizeBy: sum
		sourceColumn: items_count

		annotation SummarizationSetBy = Automatic

	column had_bundle
		dataType: string
		lineageTag: 288e43cb-2c70-4774-9455-87674f9afbac
		summarizeBy: none
		sourceColumn: had_bundle

		annotation SummarizationSetBy = Automatic

	partition transactions = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\hp\Downloads\transactions.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"transaction_id", type text}, {"session_id", Int64.Type}, {"order_date", type date}, {"gross_revenue", Currency.Type}, {"discount_amount", Currency.Type}, {"net_revenue", Currency.Type}, {"items_count", Int64.Type}, {"had_bundle", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

